version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_TAG}
    volumes:
      - post_db:/data/db
    networks:
    - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    image: ${USERNAME_HUB}/ui:${SERVICE_VER}
    ports:
      - ${EXT_PORT}:${INT_PORT}/tcp
    networks:
    - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    image: ${USERNAME_HUB}/post:${SERVICE_VER}
    networks:
    - back_net
    - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    image: ${USERNAME_HUB}/comment:${SERVICE_VER}
    networks:
    - back_net
    - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:
  comment_db:    

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${FRONT_NET_SUBNET}
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACK_NET_SUBNET}
