version: '3'
services:

  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

  fluentd:
    image: st0rik/fluentd  
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: mrgreyves/elasticsearch:7.13.1
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: mrgreyves/kibana:7.13.1
    ports:
      - "5601:5601"

networks:
  back_net:
  front_net:
